version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: nextjs-task-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - nextjs-task-db-data:/var/lib/postgresql/data
      - ./build/local/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  nextjs:
    build:
      context: ./next
    container_name: nextjs-task-app
    restart: always
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  nextjs-task-db-data:
